<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jexl</string>
	</array>
	<key>name</key>
	<string>Java Expression Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.jexl</string>
		</dict>
		<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.jexl</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.source.cs</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([+-])?\d+(\.)?\d*\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>

		<dict>
			<key>match</key>
			<string>\bnew\b|\bif\b|\belse\b|\bwhile\b|\bfor\b|\breturn\b|\bvar\b</string>
			<key>name</key>
			<string>keyword.control.jexl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\:|,|;||\btest\b\bbye\b|\bdef\b|\bimport\b|\bas\b|\^|\||\+|\-|\*|\/|\=|\(|\)|\{|\}|\[|\]|&amp;|&lt;|&gt;|~|!|\beq\b|\blt\b|\bgt\b|\ble\b|\bge\b|\band\b|\bor\b|\bnot\b|@</string>
			<key>name</key>
			<string>keyword.operator.jexl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[a-zA-Z]+:[a-zA-Z_]+|\{\S+\}|\*\* \S+|^@@|^\$\$|\b&lt;\-|\$[a-z0-9_]*|\btrue\b|\bfalse\b|\bnull\b|\bint\b|\bdouble\b|\blong\b|\bsub\b|\btime\b|\bbool\b|\bstr\b|\blist\b|\bset\b|\blistLiteral\b|\barray\b|\barrayFromList\b|\bsize\b|\bwithin\b|\bdict\b|\brange\b|\bempty\b|\bsqlmath\b|\btypeof\b|\bfilter\b|\bdefined\b|\b_\S+_\b</string>
			<key>name</key>
			<string>support.language.jexl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[_a-zA-Z][_a-zA-Z0-9]*|__[0-9]+|@[0-9]+</string>
			<key>name</key>
			<string>variable.language.jexl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b_.+_\b</string>
			<key>name</key>
			<string>keyword.other.jexl</string>
		</dict>

		<dict>
			<key>match</key>
			<string>"(?:[^"\\]|\\.)*"</string>
			<key>name</key>
			<string>string.double_quoted.jexl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'(?:[^'\\]|\\.)*'</string>
			<key>name</key>
			<string>string.single_quoted.jexl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jexl</string>
	<key>uuid</key>
	<string>3311c28d-137b-4a33-a45d-95ae68a9e529</string>
</dict>
</plist>
